name: ima2_habeesjobs
description: A new Flutter IM application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.6+7236

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  provider: ^5.0.0

  head_image_cropper:
    git:
      url: https://github.com/rdchgaa/head_image_cropper.git
      ref: 82a7b41
#  lpinyin: ^2.0.3
  flutter_widget_from_html_core: ^0.7.0
  xxc_flutter_utils:
    git:
      url: https://github.com/rdchgaa/xxc_flutter_utils.git
      ref: 0bf9a42
  path_provider: ^2.0.2
  url_launcher:
    path: plugins/url_launcher
  package_info_plus: ^1.3.0
  flutter_cache_manager: ^2.1.2
  image_picker: 0.8.4+8

  vibration:
    path: plugins/vibration

  permission_handler: 8.1.4+2

  fixnum: ^1.0.1
  adobe_xd: ^2.0.1
  flutter_svg: 1.0.3

  audioplayers: 4.1.0
  audio_session: 0.0.11
  extended_image: 6.4.1
  flutter_shaders: 0.1.2
  scratcher: 2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  shaders:
    - shaders/page_curl.frag
  assets:
    - assets/
    - assets/languages/
    - assets/emojis/
    - assets/images/
    - assets/html/zh/
    - assets/html/en/
